# Generated by Django 5.2.3 on 2025-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '1(重要)'), (2, '2'), (3, '3(まあまあ重要)'), (4, '4'), (5, '5(できれば)')], default=3),
        ),
    ]
